### PR TITLE
Add ClusterHealth API to check the cluster health

### PR DESCRIPTION
**Pull request by Praveenrajmani**
This will hit `/minio/health/cluster` anonymous API to check the cluster health

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
why don't we enhance the HealthCheck API that runs on a continuous basis?

```
// HealthCheck starts a healthcheck to see if endpoint is up. Returns a context cancellation function
// and and error if health check is already started
func (c *Client) HealthCheck(hcDuration time.Duration) (context.CancelFunc, error) {
        if atomic.LoadInt32(&c.healthStatus) == online {
                return nil, fmt.Errorf("health check is running")
        }
        if hcDuration < 1*time.Second {
                return nil, fmt.Errorf("health check duration should be atleast 1 second")
        }
        ctx, cancelFn := context.WithCancel(context.Background())
        atomic.StoreInt32(&c.healthStatus, online)
        probeBucketName := randString(60, rand.NewSource(time.Now().UnixNano()), "probe-health-")
        go func(duration time.Duration) {
                timer := time.NewTimer(duration)
                defer timer.Stop()
                for {
                        select {
                        case <-ctx.Done():
                                atomic.StoreInt32(&c.healthStatus, unknown)
                                return
                        case <-timer.C:
                                timer.Reset(duration)
                                // Do health check the first time and ONLY if the connection is marked offline
                                if c.IsOffline() {
                                        gctx, gcancel := context.WithTimeout(context.Background(), 3*time.Second)
                                        _, err := c.getBucketLocation(gctx, probeBucketName)
                                        gcancel()
                                        if IsNetworkOrHostDown(err, false) {
                                                // Still network errors do not need to do anything.
                                                continue
                                        }
                                        switch ToErrorResponse(err).Code {
                                        case "NoSuchBucket", "AccessDenied", "":
                                                atomic.CompareAndSwapInt32(&c.healthStatus, offline, online)
                                        }
                                }
                        }
                }
        }(hcDuration)
        return cancelFn, nil
}
```

and also `mc ready` is it one time activity or would it basically run for some time and exit? 

Because if we need `mc ready` to do only one time we can just do it using `curl`

**Comment by klauspost** [comment]
@Praveenrajmani @harshavardhana Why are we adding minio specific calls to `minio-go` and not `madmin-go`?

**Comment by harshavardhana** [comment]
> @Praveenrajmani @harshavardhana Why are we adding minio specific calls to `minio-go` and not `madmin-go`?

Actually we can add it to madmin-go that might be the right place for this.

**Comment by Praveenrajmani** [comment]
As discussed, we can re-use the existing `HealthCheck` implementation. Closing this PR.

**Pull request closed without merging**
