### PR TITLE
Add tests to check if ListObjects/V2 returns expected StorageClass

### PR DESCRIPTION
**Pull request by nitisht**
See https://github.com/minio/minio/issues/5754

### CODE REVIEW

**Comment by nitisht** [comment]
Updated @poornas PTAL

**Comment by deekoder** [comment]
Should we ignore travis failure?

**Comment by nitisht** [comment]
IMO, we can wait till play is updated

**Comment by kannappanr** [comment]
@nitisht @deekoder minio/minio#5766  has been merged. I restarted Travis build succeeded. Can we now merge this PR?

**Comment by deekoder** [comment]
Yes, we can @kannappanr. Doing so now.

**Pull request merged**
