### PR TITLE
#1552 add functional tests for bucket tagging

### PR DESCRIPTION
**Pull request by romanchechyotkin**

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Comment by klauspost** [comment]
LGTM, but just merge them into a single test. It seems reasonable to test them together. 

You can explore the API limitations if you'd like and check if we are being strict with the limits:

> The tag key is a case-sensitive string that can contain 1 to 128 Unicode characters.

> The tag value. The tag value is a required string.  [...] The tag value is a case-sensitive string that can contain from 0 to 256 Unicode characters.

I am not too sure we actually check these - which should be done [here](https://github.com/minio/minio-go/blob/aadf94623806731617fda2c8a8624028f157a154/pkg/tags/tags.go#L256)

Maybe also check Get and Delete before any tagging has been set.

**Comment by klauspost** [comment]
@harshavardhana Quickest draw of the West :D

**Comment by harshavardhana** [comment]
> LGTM, but just merge them into a single test. It seems reasonable to test them together.
> 
> You can explore the API limitations if you'd like and check if we are being strict with the limits:
> 
> > The tag key is a case-sensitive string that can contain 1 to 128 Unicode characters.
> 
> > The tag value. The tag value is a required string.  [...] The tag value is a case-sensitive string that can contain from 0 to 256 Unicode characters.
> 
> I am not too sure we actually check these - which should be done [here](https://github.com/minio/minio-go/blob/aadf94623806731617fda2c8a8624028f157a154/pkg/tags/tags.go#L256)
> 

These API limits are server driven, basically AWS S3 magically changes these things whenever there is AWS Reinvent in Vegas. Adding API checks on client side can break things easily.

This happened in the past multiple times.

A test to return errors from server is a good thing to add. You can explore adding  these things 

https://github.com/minio/mint/blob/efe113e7aed81ed6ceb200e5e644198ea06e0e27/build/versioning/tagging.go#L34

https://github.com/minio/mint/blob/efe113e7aed81ed6ceb200e5e644198ea06e0e27/run/core/aws-sdk-go/main.go#L539

This was the main reason we didn't bother to finish these tests in this SDK as it's already kind of tested for the server.

**Comment by klauspost** [comment]
@harshavardhana This code is actually used in MinIO server as well.

**Comment by harshavardhana** [comment]
> @harshavardhana This code is actually used in MinIO server as well.

Oh then we can definitely add.

**Pull request merged**
