### PR TITLE
Fixes the timeout issue in 'GetObjectWithContext' api

### LINKED ISSUE #241: Disallow any other endpoint other than https://s3.amazonaws.com

### PR DESCRIPTION
**Pull request by ebozduman**
Shortened the timeout from 1 Millisecond to 1 Nanosecond.
Fixes https://github.com/minio/mint/issues/241

### CODE REVIEW

**Comment by poornas** [comment]
@ebozduman , could you please also change the other tests that use 1 millisecond timeout?

**Comment by ebozduman** [comment]
Added the same fix to all other tests with timeouts.

**Comment by ebozduman** [comment]
Rebased.

**Comment by poornas** [comment]
travis failures need to be fixed.

**Comment by ebozduman** [comment]
Fixed the travis failure, tested and rebased.

**Pull request merged**
