### PR TITLE
added shield to RapidAPI

### PR DESCRIPTION
**Pull request by amelia-wilson**
Hey there. I added a link in your README to a tool where you can test out AmazonS3 API calls in your browser before using your SDK to connect to the API. I've added it to these other SDKs (Telegram, Shopify and LinkedIn) and gotten feedback that it was pretty useful. If anything, let me know what you think and if you have any feedback. I'm part of the team that built this tool and we're always looking to make it better!

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
@amelia-wilson minio-go is AWS-S3 client library, how will rapid-API be useful for us?

**Comment by amelia-wilson** [comment]
@krishnasrinivas Rapid will help out users interested in your client library test out the API in the browser before implementing the API in code. They can visually see the JSON response and ultimately ensure their parameters are working. :)

**Comment by krishnasrinivas** [comment]
@amelia-wilson going by the description on rapidapi.com it looks like a one stop solution for all the API services. It is more directed to app developers who are using using multiple libraries for multiple services. What your service provides developers is a single library interface to interact with any service. This is not useful for minio-go or its consumers.

**Comment by harshavardhana** [comment]
Closing as out of scope.

**Pull request closed without merging**
