### PR TITLE
Api: Add PutObjectWithContext, GetObjectWithContext, FPutObjectWithCo…

### LINKED ISSUE #700: Support for context.Context?
Hi,

are there plans to support request cancellation via `context.Context`? I'm currently in the progress of adding proper cancellation to restic, and I'd like to be able to cancel outgoing requests to the s3 backend...

Cheers,
Alex

### PR DESCRIPTION
**Pull request by poornas**
Fixes #700. 

Add PutObjectWithContext, GetObjectWithContext, FPutObjectWithContext, FGetObjectWithContext calls to facilitate request cancellation.

### CODE REVIEW

**Comment by krisis** [comment]
@poornas is it decided that https://github.com/minio/minio-go/issues/747 will be fixed after adding these APIs with cancellation feature?

**Comment by poornas** [comment]
@krisis, we will need to discuss that in tomorrow'w meeting.

**Comment by deekoder** [comment]
Need to discuss this wrt to #747

**Comment by poornas** [comment]
closing this on account of #811 which has context support.

**Pull request closed without merging**
