### PR TITLE
trie: new package

### PR DESCRIPTION
**Pull request by balamurugana**
This implements a simple trie tree for minio server/tools.
This package borrows idea from
https://godoc.org/golang.org/x/text/internal/triegen.

### CODE REVIEW

**Comment by harshavardhana** [comment]
why is this needed @balamurugana ? and why in minio-go

**Comment by harshavardhana** [comment]
We shouldn't move / dump packages in minio-go if they are not going to be used directly. If its used somewhere then you can create a `pkg/trie`

Also this code looks like comes from - https://github.com/minio/minio/blob/master/cmd/trie.go we can have "pkg/trie" on the server

**Comment by balamurugana** [comment]
@harshavardhana mc and minio have same copy of trie hence making it as pkg

**Comment by balamurugana** [comment]
@harshavardhana got it

**Comment by balamurugana** [comment]
moved to https://github.com/minio/minio/pull/3729

**Pull request closed without merging**
