### PR TITLE
api: Upon failure abort the multipart upload.

### PR DESCRIPTION
**Pull request by harshavardhana**
Since we do not have resuming capabilities we
should not leave stale parts behind upon any
error during putObject(). This PR pro-actively
aborts the multipart upload created during
the putObject() for large files.

### CODE REVIEW

**Comment by vadmeste** [comment]
LGTM though I think this PR is not so much useful in practice. I think most of the stale uploads are due to a premature exit during multipart upload.

**Comment by harshavardhana** [comment]
> LGTM though I think this PR is not so much useful in practice. I think most of the stale uploads are due to a premature exit during multipart upload.

This is similar in behavior to how aws-sdk upload manager does. Lets say if one of the parts failed to upload we will never be able to clear it unless user explicitly does it on his own, most users are not aware. We should disallow that to happen and just abort the entire request similarly how aws-sdk does this.

**Comment by vadmeste** [comment]
> This is similar in behavior to how aws-sdk upload manager does. Lets say if one of the parts failed to upload we will never be able to clear it unless user explicitly does it on his own, most users are not aware. We should disallow that to happen and just abort the entire request similarly how aws-sdk does this.

I know, but in practice if a part fails to upload due to a down server or internet connection (I don't see other possible errors here), I think that most likely the next call which aborts upload would fail (but I know not always).

I will approve this PR.

Can you rebase this @harshavardhana  ?

**Comment by harshavardhana** [comment]
> I know, but in practice if a part fails to upload due to a down server or internet connection (I don't see other possible errors here), I think that most likely the next call which aborts upload would fail (but I know not always).

Not necessarily with AWS a part might fail just because of some slow network whereas an abort might complete. it can also happen that input stream is somewhat corrupted as well due to a local filesystem error.  So there are valid cases.. not just network alone.

**Comment by harshavardhana** [comment]
Any reviews ?

**Comment by harshavardhana** [comment]
@donatello any reviews?

**Pull request merged**
