### PR TITLE
Add tests for SSE-C,SSE-S3 encryption

### PR DESCRIPTION
**Pull request by poornas**
This is blocked on https://github.com/minio/minio/pull/6488 and Mint update to run server with MINIO_SSE_MASTER_KEY env set

### CODE REVIEW

**Comment by poornas** [comment]
@harshavardhana , yes it can be reviewed.

**Comment by nitisht** [comment]
ping @aead

**Comment by kannappanr** [comment]
Marking this as blocked until an environment variable is introduced to run SSE-S3 tests similar to the one in minio-dotnet

**Comment by poornas** [comment]
@vadmeste and @aead, can you reapprove - added a env variable ENABLE_KMS to run SSE-S3 functional tests only when kms is set up

**Pull request merged**
