### PR TITLE
Add missing doneCh in the example for removeobjects

### PR DESCRIPTION
**Pull request by oivoodoo**

### CODE REVIEW

**Comment by harshavardhana** [comment]
We do not need a doneCh this code to meant to drain out all objects. Once there are no more objects the objectsCh is closed automatically.

**Comment by oivoodoo** [comment]
Its producing the issue in the code because of the usage of doneCh var.

**Comment by harshavardhana** [comment]
Also this same code is being fixed by another PR #949

**Comment by harshavardhana** [comment]
Sorry this PR accidentally got closed...

**Pull request merged**
