### PR TITLE
s3utils: Support AWS S3 US GovCloud endpoint.

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes https://github.com/minio/minio/issues/4489

### CODE REVIEW

**Comment by vadmeste** [comment]
I tried to create a new bucket in us-gov-west-1 but it did give me:
```
$ go run makebucket.go
2017/06/11 21:01:44 The specified location-constraint is not valid
exit status 1
```

I am not even sure that this is supposed to work with our s3 account. @harshavardhana, do you have any idea ?

**Comment by harshavardhana** [comment]
> I am not even sure that this is supposed to work with our s3 account. @harshavardhana, do you have any idea ?

It won't work you need a special account like china. @vadmeste It is being validated upstream by mattermost folks. We can only review if the code is correct and working.

**Comment by vadmeste** [comment]
One little problem with PR is it has a regression concerning creating a bucket with a region that doesn't match to the Minio server's region (AWS S3 is fine). Here is the log:

```
$ go run makebucket.go                                                                                                                                                   
---------START-HTTP---------
PUT /bucket-3/ HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/2.1.0
Content-Length: 153
Authorization: AWS4-HMAC-SHA256 Credential=minio/20170615/us-west-2/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=bc07bd248b47da97cd1bf3898c2f75ed3fcffb0ccb32fb0d0b3dddacc14bb4e3
Content-Md5: Op2YSFwhrUHkWAAirYWTWQ==
X-Amz-Content-Sha256: a4a3d263179bfcbaf88755b14ea9db3048e4179c03bbc94ccf0f13c8c2d3df6a
X-Amz-Date: 20170615T171741Z
Accept-Encoding: gzip

HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/xml
Date: Thu, 15 Jun 2017 17:17:41 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14C85B1E21AB8870

ee
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRegion</Code><Message>Region does not match.</Message><Key></Key><BucketName></BucketName><Resource>/bucket-3/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0
---------END-HTTP---------
2017/06/15 18:17:41 Put http://localhost:9000/bucket-3/: http: ContentLength=153 with Body length 0
exit status 1
```

**Comment by harshavardhana** [comment]
> 0
> ---------END-HTTP---------
> 2017/06/15 18:17:41 Put http://localhost:9000/bucket-3/: http: ContentLength=153 with Body length 0
> exit status 1

Looks like there is a bug in retry @vadmeste - let me check why.

**Comment by vadmeste** [comment]
To reproduce this, you can call `MakeBucket("mybucket", "us-west-2")` where the region of Minio server is the default one (`us-east-1`)

**Comment by harshavardhana** [comment]
> To reproduce this, you can call MakeBucket("mybucket", "us-west-2") where the region of Minio server is the default one (us-east-1)

Yep found it!

**Comment by harshavardhana** [comment]
@jwilander would you mind validating this PR again we made some more changes.. related to location handling etc.

**Comment by jwilander** [comment]
Passed the new build along to the customer and they're reporting seeing `Amazon S3 endpoint should be 's3.amazonaws.com'.` when trying to put objects

**Comment by harshavardhana** [comment]
> Passed the new build along to the customer and they're reporting seeing Amazon S3 endpoint should be 's3.amazonaws.com'. when trying to put objects

This is strange and should not happen. Let me check again.

**Comment by jwilander** [comment]
Actually it looks the build I gave them was built without the patch by accident. Sorry about that I'll try again with a proper build

**Comment by harshavardhana** [comment]
> Actually it looks the build I gave them was built without the patch by accident. Sorry about that I'll try again with a proper build

Oh no problem. Thanks @jwilander

**Comment by jwilander** [comment]
Hi @harshavardhana, just wondering what's the release schedule look like? We'd like to include this in our next Mattermost release (merge deadline is in a few weeks) if possible. Not a big deal if there isn't a release until after, we can always use a temporary fork with these changes applied. Apologies if this is documented somewhere, I couldn't find anything on it after a quick look around

**Comment by harshavardhana** [comment]
> Hi @harshavardhana, just wondering what's the release schedule look like? We'd like to include this in our next Mattermost release (merge deadline is in a few weeks) if possible. Not a big deal if there isn't a release until after, we can always use a temporary fork with these changes applied. Apologies if this is documented somewhere, I couldn't find anything on it after a quick look around

Generally you can just vendorize from the master.. for Go we don't necessarily do this. But if you wish to have a tagged release we can do that as well. @jwilander

**Comment by jwilander** [comment]
If it's not too much trouble a tagged release would be great

**Comment by harshavardhana** [comment]
> If it's not too much trouble a tagged release would be great

Waiting for couple of other patches before we can proceed to tag.

**Pull request merged**
