### PR TITLE
Add Client.PresignedHeadObject method

### PR DESCRIPTION
**Pull request by dmage**
Added a method to get a presigned URL to access an object [metadata](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html) without credentials.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Can you explain a bit more about this ? why is this needed which is not achieved by PresignedGetObject() ?

**Comment by dmage** [comment]
I'm implementing yet another S3 driver for [Docker Distribution](https://github.com/docker/distribution). And Docker uses HEAD requests to check if the layer of an image is already uploaded. If I redirect the Docker client to PresignedGetObject URL while it performs a HEAD request, it will get 403, because the URL is signed for the different method.

**Comment by harshavardhana** [comment]
> I'm implementing yet another S3 driver for Docker Distribution. And Docker uses HEAD requests to check if the layer of an image is already uploaded. If I redirect the Docker client to PresignedGetObject URL while it performs a HEAD request, it will get 403, because the URL is signed for the different method.

Curious does current implementation of S3 driver of any presigned operations, why is it necessary to use presigned operations? is this URL being shared to some other entity which would validate upon the object? 

Another question is why a new S3 driver any improvements that you have in mind that you can share with us?

**Comment by dmage** [comment]
> does current implementation of S3 driver use any presigned operations

[Yes, it does.](https://github.com/docker/distribution/blob/e18fe7d3f4573faac5a32a0df3322a4812969c92/registry/storage/driver/s3-aws/s3.go#L859-L874)

They are used to take off workload from the docker registry. For example, when you say `docker pull minio/minio`, Docker gets from Docker Hub presigned redirects to image layers. So it saves bandwidth on the registry servers.

It doesn't save bandwidth in case of HEAD request, though. I need to investigate it further.

> why a new S3 driver

Current implementation uses aws-sdk-go which AFAIK does not support chunked uploads. It means that you need at least a 5 MB buffer to sign an upload part. This causes OOM if a burst of uploads come to our registry.

**Comment by harshavardhana** [comment]
> They are used to take off workload from the docker registry. For example, when you say docker pull minio/minio, Docker gets from Docker Hub presigned redirects to image layers. So it saves bandwidth on the registry servers.
> 
> It doesn't save bandwidth in case of HEAD request, though. I need to investigate it further.
> 
> why a new S3 driver
> Current implementation uses aws-sdk-go which AFAIK does not support chunked uploads. It means that you need at least a 5 MB buffer to sign an upload part. This causes OOM if a burst of uploads come to our registry.

Understood now. Here are few things i have in mind. 

In a scenario like this i think we can make Presign little generic? like for rest of all object operations? .. like an API like this. 

```
PresignURL(method string, bucketName, objectName string, expiry time.Duration, reqParams url.Values)

Usage: 

PresignURL(http.MethodHead, "testbucket", "myobject", time.Hour * 1,  url.Values{})
```

https://github.com/minio/minio-go/blob/master/api-presigned.go#L40  we already have an internal code which can be exposed. i.e just rename it as PresignURL. 

I am of the opinion that it kind of doesn't make sense to add new API's for HEAD - since there are hardly users for presigned HEAD, DELETE, POST etc. and they are not required to be first class APIs.

Will check with @abperiasamy and get back to you if we can make it explicit or have a single function for rest of the HTTP methods ops.

**Comment by harshavardhana** [comment]
// cc @deekoder we need to discuss this with @abperiasamy on the final API for presignedHeadObject.

**Comment by harshavardhana** [comment]
We have decided to implement this API @dmage thanks for sending this over. Can you rebase to master and 

  - Add functional tests
  - Update the relevant API doc in docs/API.md 
  - Add an example at `examples/s3/presignedhead-object.go` 

Thanks for the PR and sorry for the delay.

**Comment by harshavardhana** [comment]
This is already merged after adding documentation and tests, closing this PR.

**Pull request closed without merging**
