### PR TITLE
Update env vars to meaningful names

### PR DESCRIPTION
**Pull request by NitishT**
- Changed environment var S3_ADDRESS to SERVER_ENDPOINT
 - Changed environment var S3_SECURE to ENABLE_HTTPS

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
I think it is better to prefix the env vars by `MINIO_TEST_`

MINIO_TEST_ENDPOINT
MINIO_TEST_ACCESS_KEY
MINIO_TEST_SECRET_KEY
MINIO_TEST_ENABLE_HTTPS

**Comment by harshavardhana** [comment]
> MINIO_TEST_ENDPOINT
> MINIO_TEST_ACCESS_KEY
> MINIO_TEST_SECRET_KEY
> MINIO_TEST_ENABLE_HTTPS

Perhaps we can use these consistently across all libraries.. :+1:

**Comment by NitishT** [comment]
Minio SDKs will run against a target that is S3 compatible. So, I thought adding MINIO/S3 will be redundant. 

@krisis yes, that will be better. I will do it

**Comment by NitishT** [comment]
Added constants

```
const (
	serverEndpoint = "SERVER_ENDPOINT"
	accessKey      = "ACCESS_KEY"
	secretKey      = "SECRET_KEY"
	enableSecurity = "ENABLE_HTTPS"
)
```

**Pull request merged**
