### PR TITLE
Avoid changing '+' to space when request object

### PR DESCRIPTION
**Pull request by soolaugust**
Fix https://github.com/minio/minio-go/issues/1177

### CODE REVIEW

**Comment by soolaugust** [comment]
I notice travis-ci report an error:

image

I couldn't see any issue for this, as PathUnescape  is identical to QueryUnescape except that it does not unescape '+' to ' ' (space).

So could you help to check this, thanks :)

**Comment by soolaugust** [comment]
this is not the reason, will close it. more informations, please refer to https://github.com/minio/minio-go/issues/1177

**Comment by aofei** [comment]
Hi @soolaugust,

Sorry to comment in a closed PR, but why is this closed? I can't think of the reason, it seems that this PR is correct.

My scenario is to connect all of my AWS S3 API compatible storage services only using [minio/minio-go](https://github.com/minio/minio-go). I encountered a series of problems these days and eventually found out that [`minio.Core. listObjectsQuery`](https://github.com/minio/minio-go/blob/3721161a9e0f2ae10a2d8f0da88938ab2eeb99c1/api-list.go#L419) converted all `+` in my filenames into spaces, which is wrong. It's all because [`minio.Core. listObjectsQuery`](https://github.com/minio/minio-go/blob/3721161a9e0f2ae10a2d8f0da88938ab2eeb99c1/api-list.go#L419) used [`url.QueryUnescape`](https://godoc.org/net/url#QueryUnescape) instead of [`url.PathUnescape`](https://godoc.org/net/url#PathUnescape).

To reproduce this, just create a file named `example.com/foo/bar/@v/v2.3.4+incompatible.info` in any AWS S3 API compatible storage service (such as GCS) and use [`minio.Client.ListObject`](https://godoc.org/github.com/minio/minio-go#Client.ListObjects) to get it.

/cc @vadmeste here from https://github.com/minio/minio-go/issues/1177#issuecomment-544855996.

**Comment by soolaugust** [comment]
Hi @aofei , in your scenario, this issue will produce. because the new minio server version have correct this issue. if you want to use minio-go to connect S3 API compatible storage services, you need to correct from server side.

but I think your advice is correct, minio-go should consider such scenario. what's your opinion @vadmeste and @harshavardhana

**Comment by vadmeste** [comment]
@aofei 

If you test with AWS S3, listing objects when url encoding is set to 'url' does not return key names with '+'. It returns with '%2B'

Although I am not able to find any reference about how URL encoding works exactly, I followed the behavior of AWS S3.

But I still think using QueryUnescape or PathUnescape will behave exactly the same in this case, were you testing with GCS ?

**Comment by aofei** [comment]
@vadmeste 

I just checked GCS, and it also uses "%2B". Weird...

... I can't get my cloud service provider to change because I think that would cause them to break others, so they will definitely refuse anyway.

However, I still feel that using [`url.PathUnescape`](https://godoc.org/net/url#PathUnescape) is the right approach. Because we're working on paths, aren't we? Also, replacing it with [`url.PathUnescape`](https://godoc.org/net/url#PathUnescape) solved my problem.

And, of course, I understand your concern, maybe we can do some special treatments for AWS S3's "%2B" after using [`url.PathUnescape`](https://godoc.org/net/url#PathUnescape). Like this:

```go
...
listBucketResult.Contents[i].Key, err = url.PathUnescape(obj.Key)
...
listBucketResult.Contents[i].Key = strings.Replace(listBucketResult.Contents[i].Key, "%%2B", " ", -1)
...
```

This way we can adapt to both situations. And this isn't a stupid solution, because the only difference between [`url.QueryUnescape`](https://godoc.org/net/url#QueryUnescape) and [`url.PathUnescape`](https://godoc.org/net/url#PathUnescape) is that [`url.PathUnescape`](https://godoc.org/net/url#PathUnescape) does not unescape '+' to ' ' (space).

What do you think?

**Comment by harshavardhana** [comment]
@aofei if your provider doesn't work like AWS S3 then we can't do anything here. Please ask them to fix this on server.

**Comment by aofei** [comment]
> @aofei if your provider doesn't work like AWS S3 then we can't do anything here. Please ask them to fix this on server.

This is really a great reply, it perfectly ignores my concerns and my proposal, thank you very much @harshavardhana.

And @vadmeste, just like you said, there doesn't seem to be a reference about how URL encoding works exactly, which shows that it may not be "standardized". So do you think we should consider the situation that using "+" instead of "%2B"?

And FYI, the [`aws/aws-sdk-go`](github.com/aws/aws-sdk-go)'s [`s3.ListObjects`](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#ListObjectsInput) worked as expected. But I love [`minio/minio-go`](https://github.com/minio/minio-go) more (the [`aws/aws-sdk-go`](github.com/aws/aws-sdk-go) is too ugly). So please think about it. 🥺

**Comment by harshavardhana** [comment]
@aofei you need to use `url` encoding  with aws-sdk-go - are you sure that is how you used?

**Pull request closed without merging**
