### PR TITLE
Add get bucket versioning

### PR DESCRIPTION
**Pull request by clook**
Implement GetBucketVersioning

### CODE REVIEW

**Comment by harshavardhana** [comment]
what is the purpose of just adding GetBucketVersioning? @clook

**Comment by clook** [comment]
Hi @harshavardhana, the goal is to be able to get the versioning status of bucket (https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketVersioning.html).

Currently, I'm using https://github.com/aminueza/terraform-provider-minio which relies on minio-go but am unable to provision a bucket with versioning configuration. I could easily make a PR for https://github.com/aminueza/terraform-provider-minio if `GetBucketVersioning` is supported.

**Comment by harshavardhana** [comment]
> Currently, I'm using https://github.com/aminueza/terraform-provider-minio which relies on minio-go but am unable to provision a bucket with versioning configuration. I could easily make a PR for https://github.com/aminueza/terraform-provider-minio if `GetBucketVersioning` is supported.

@clook thanks for the explanation - it makes sense, but what is the pre-requisite of using bucket versioning with Terraform?

**Comment by clook** [comment]
> @clook thanks for the explanation - it makes sense, but what is the pre-requisite of using bucket versioning with Terraform?
The pre-requesite for the Terrraform provider is to be able to compare the Terraform current known state with the real resource state and then guess if it has to apply `DisableVersioning` or `EnableVersioning` or not.
Without knowing the real resource state, we would be forced to update the resource even if no change is necessary.

**Comment by clook** [comment]
Also tell me if you want some unit tests to be performed. Right now, I mostly templated over `GetBucketEncryption` and tested my branch with a PR on the actual Terraform provider.

**Pull request merged**
