### PR TITLE
Fix go module imports properly to honor semantic versioning

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by admoriarty** [comment]
Hey, sorry for hijacking a closed PR, but I cannot any other guide as to why a local project which was building lately is now broken because of this v6 change...is it intended to be a breaking change? I get lots of 
`package github.com/minio/minio-go/v6/pkg/credentials: cannot find package "github.com/minio/minio-go/v6/pkg/credentials" in any of:
	/usr/local/go/src/github.com/minio/minio-go/v6/pkg/credentials (from $GOROOT)
	/home/jenkins/go/src/github.com/minio/minio-go/v6/pkg/credentials (from $GOPATH)`
I tried updating all my imports of this package to be /v6 but I still get a resolution issue....is it my version of Go thats at fault. Are there some notes about how to soak up such a change, or fix back to a version previous to this PR? Any tips appreciated!

**Comment by deliciouslytyped** [comment]
@admoriarty I also ran into this and need a fix. (Is there any way to get `go get` to use a specific repository commit?)

**Comment by harshavardhana** [comment]
You need to use `go mod` @admoriarty @deliciouslytyped

**Comment by harshavardhana** [comment]
https://github.com/golang/go/wiki/Modules#semantic-import-versioning @admoriarty @deliciouslytyped

**Comment by admoriarty** [comment]
I've tried... 
- updating from 1.10 to 1.12 of the golang image we build the app on
- updating all our minio imports to mention /v6 at the end
- calling `go mod` and or `go mod github.com/minio/minio-go`
Despite all of this I'm still getting complaints along the lines of cannot find ... /v6 ... paths

**Comment by harshavardhana** [comment]
You are not doing it correctly @admoriarty first your code should depend on minio-go and then you have to go mod tidy to get the latest released version of minio-go

You have to follow the go mod instructions and it will work fine.

**Comment by harshavardhana** [comment]
Take a look at how to use it https://github.com/minio/mc/pull/2782/files

**Pull request merged**
