### PR TITLE
Add custom MD5/SHA256 hasher option

### PR DESCRIPTION
**Pull request by klauspost**
Since there is no cleanup for the API clients using the SIMD MD5 needs to be up to the API users to manage.

Provide a function that allows to insert a custom hasher for MD5 and SHA256.

We keep using the same for both, but by default we allow to reuse the hashers.

### CODE REVIEW

**Comment by fwessels** [comment]
Code looks good, but need to sort of the md5-simd buffer copy issue first.

**Comment by harshavardhana** [comment]
> EDIT: Maybe wait until we've found out how to make md5-simd performant.

Do we need it anymore? @klauspost

**Comment by klauspost** [comment]
@harshavardhana I have kept the default to be a wrapped stdlib, but added a wrapper that will allow reuse of the hashers.

I think this will be a fine improvement and it gives the flexibility to override them on clients.

**Comment by harshavardhana** [comment]
PTAL @fwessels

**Pull request merged**
