### PR TITLE
remove sha256-simd support we do not need it anymore

### PR DESCRIPTION
**Pull request by harshavardhana**
we have moved to go1.21 as the least Go version we would support 
for minio-go/v7 - and move to crypto/sha256

### CODE REVIEW

**Review by fwessels — APPROVED** [review]
LGTM

**Review by donatello — APPROVED** [review]

**Comment by sergeevabc** [comment]
Does crypto/sha256 work on processors without SSE4 and AVX?

**Comment by harshavardhana** [comment]
> Does crypto/sha256 work with processors without SSE4 and AVX?

This processor is from 2007, sure you can use it don't expect performance.

**Comment by sergeevabc** [comment]
> This processor is from 2007, sure you can use it don't expect performance.

Performance is good, thank you. Keep it that way, because there are a [lot of places](https://en.wikipedia.org/wiki/Favela) outside your rich neighborhoods where people don't upgrade regularly, they have other priorities and opportunities.

**Pull request merged**
