### PR TITLE
feat: add aws ap-southeast-4 region

### PR DESCRIPTION
**Pull request by ianmuge**
feat: add aws ap-southeast-4 region

### CODE REVIEW

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by klauspost — APPROVED** [review]

**Comment by ianmuge** [comment]
The build seems to succeed locally but not on GA

**Comment by klauspost** [comment]
Yeah, fix is in #1768

**Comment by ianmuge** [comment]
I shall just wait for the fix to be merged then, thanks

**Comment by vadmeste** [comment]
> I shall just wait for the fix to be merged then, thanks

@ianmuge you can rebase your PR and push it again. The fix is just merged

**Comment by ianmuge** [comment]
ready

**Comment by klauspost** [comment]
Thanks!

**Pull request merged**
