### PR TITLE
GetObject: Don't set objectInfo until first read/seek/stat call

### PR DESCRIPTION
**Pull request by awwalker**
Fixes: #501 

adds test case where #501 happens as well.

### CODE REVIEW

**Comment by harshavardhana** [comment]
```
ineffassign .
C:\gopath\src\github.com\minio\minio-go\api-put-object.go:223:9: ineffectual assignment to err
C:\gopath\src\github.com\minio\minio-go\api_functional_v2_test.go:719:5: ineffectual assignment to n
C:\gopath\src\github.com\minio\minio-go\api_functional_v4_test.go:1086:5: ineffectual assignment to n
C:\gopath\src\github.com\minio\minio-go\api_unit_test.go:357:2: ineffectual assignment to totalPartsCount
C:\gopath\src\github.com\minio\minio-go\api_unit_test.go:357:19: ineffectual assignment to partSize
C:\gopath\src\github.com\minio\minio-go\api_unit_test.go:357:29: ineffectual assignment to lastPartSize
C:\gopath\src\github.com\minio\minio-go\api_unit_test.go:374:2: ineffectual assignment to totalPartsCount
C:\gopath\src\github.com\minio\minio-go\api_unit_test.go:374:29: ineffectual assignment to lastPartSize
Command exited with code 1
```

**Comment by awwalker** [comment]
Interesting...I don't think I edited any of those files. Why would appveyor complain all of a sudden?

**Comment by harshavardhana** [comment]
> Interesting...I don't think I edited any of those files. Why would appveyor complain all of a sudden? Even running it now locally on the same branch doesn't cause these to appear.

This only runs during windows run perhaps the tool updated itself and adds more checks. Would you fix it?

**Comment by awwalker** [comment]
Must have updated or something...all the things it wanted fixed were valid. I'll have to update my version.

**Pull request merged**
