### PR TITLE
Deprecate Source & Destination Info

### PR DESCRIPTION
**Pull request by vadmeste**
-- Notice:
-- The documentation is not updated until we approve the API
-- The functional tests are also not updated to prove this is not a breaking change

This PR changes the following structs:

*) DestinationInfo{} -> DestinationOptions{}
*) SourceInfo{} -> SourceOptions{}
*) DestInfoOptions{} -> TargetObjectInfo{}

And the following functions
*) NewDestinationInfo() -> NewDestinationOptions()
*) NewSourceInfo() -> NewSourceOptions()
*) NewDestinationInfoWithOptions() -> NewDestinationOptionsWithTargetInfo()

### CODE REVIEW

**Comment by vadmeste** [comment]
> We should migrate to v7 with this change @vadmeste you need to make necessary changes

This PR does not break anything. Also it is better if v7 has the general big API change.. (where we merge context with options ?)

**Comment by vadmeste** [comment]
@harshavardhana if we want to have this API style in v7, I think SourceInfo & DestinationInfo will be better than SourceOptions & DestinationOptions.. what do you think?

```
        obj1, err := s3Client.PutObject(ctx, "my-bucketname", "my-objectname", object, 1024, minio.PutObjectOptions{})
        if err != nil {
                log.Fatalln(err)
        }

        obj2, _ := minio.NewDestinationInfo("my-bucketname", "dstObject-1", newSSEC, map[string]string{"notmyheader": "notmyvalue"})

        // Initiate copy object.
        err = s3Client.CopyObject(ctx, obj2, obj1)
        if err != nil {
                log.Fatalln(err)
        }
```

**Comment by harshavardhana** [comment]
> @harshavardhana if we want to have this API style in v7, I think SourceInfo & DestinationInfo will be better than SourceOptions & DestinationOptions.. what do you think?
> 
> ```
>         obj1, err := s3Client.PutObject(ctx, "my-bucketname", "my-objectname", object, 1024, minio.PutObjectOptions{})
>         if err != nil {
>                 log.Fatalln(err)
>         }
> 
>         obj2, _ := minio.NewDestinationInfo("my-bucketname", "dstObject-1", newSSEC, map[string]string{"notmyheader": "notmyvalue"})
> 
>         // Initiate copy object.
>         err = s3Client.CopyObject(ctx, obj2, obj1)
>         if err != nil {
>                 log.Fatalln(err)
>         }
> ```

Yes but I think we should provide a mechanism where it is written in the form like this, a returned value of result is not directly consumable.

```
objInfo, _ := PutObject (...)

cpObjInfo, _ := CopyObject(NewDestOptions(), objInfo.ToOptions(override if any...))

.. PutObject(..., cpObjInfo.ToOptions(override if any...))

ad infinitum.. 
```

**Comment by vadmeste** [comment]
okay understood, here objInfo is different to source/dst options, will try your suggestion

**Comment by harshavardhana** [comment]
Closing this PR in favor of #1332

**Pull request closed without merging**
