### PR TITLE
Reduce memory consumption by staging the data locally.

### LINKED ISSUE #730: optimalPartInfo() default partSize results in running out of memory
Like #404, I'm streaming data which could be over 1GB and trying to use PutObjectStreaming(), but this results in optimalPartInfo(-1) being called and a partSize of 603979776 being returned.

The problem I face is that this partSize is used as, essentially, the size of the read buffer, and I'm running out of memory (I end up with errors like `fork/exec ...: cannot allocate memory` after the stream completes).

I've tried setting partSize = minPartSize in optimalPartInfo() when the input size is -1, and this solves my memory issue.

Regardless of exactly how it's done, can we get (or choose) a reasonable sized read buffer during PutObjectStreaming() so that we can stream in constant small amount of memory?

### PR DESCRIPTION
**Pull request by harshavardhana**
Fixes #730

### CODE REVIEW

**Comment by harshavardhana** [comment]
Any reviews ?

**Comment by donatello** [comment]
Could you fix the conflicts?

**Comment by harshavardhana** [comment]
> Could you fix the conflicts?

dun!

**Comment by harshavardhana** [comment]
> @harshavardhana during our design discussions long time back on sdks we had decided not to use tmp files at all, did that change anytime? because if that is the case we can use tmp files in other libs too.

@krishnasrinivas the only reason i think its valid is because of few reasons that i found that our SDKs don't work. 

PutObject() with size == -1 - atleast in Go results in 570MB , 570MB x 2 due to bytes.Buffer usage (2x growth rate).  The problem is Go GC never relinquishes this unless it hits the GC=100% mark. 

At the same time user is also concurrently uploading many such PutObject() operations for 1GiB - all of them with stream size of '-1' .  This incurs a memory growth to around multiple of GB which is not GC'ed properly due to the same fact as GC=100 growth.

There is no easier way to restrict the user, unless other than allocating a large block of 570MB re-usable memory. This would also have an impact on minio-go startup performance.

Using temporary files there are few advantages i.e 

 - The stored file never grows beyond 570MB unlike usage of bytes.Buffer. File itself is garbage collected upon error or success. 
 - There is no GC overahead or no idle memory to track. The memory footprint of minio-go is around 30MB~50MB. 

This is the problem which affects all our libraries.

**Comment by harshavardhana** [comment]
We should moved this as blocked for now on discussion with @abperiasamy

**Comment by harshavardhana** [comment]
Closing this doing bufPool approach. We have a full API refactor #747

**Pull request closed without merging**
